#  Licensed under the Apache License, Version 2.0 (the "License"); you may
#  not use this file except in compliance with the License. You may obtain
#  a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.

Version: 2

Application:
  ?:
    type: com.example.docker.DockerOrion
  name: $.appConfiguration.name
  host: $.appConfiguration.host
  publish: $.appConfiguration.publish
  mongodb: $.mongoConfig.mongoDB

Forms:
  - appConfiguration:
      fields:
        - name: license
          type: string
          description: Apache License, Version 2.0
          hidden: true
          required: false
        - name: name
          type: string
          label: Application Name
          initial: 'DockerOrion'
          description: >-
            Enter a desired name for the application. Just A-Z, a-z, 0-9, dash and
            underline are allowed
        - name: host
          type:
            - com.mirantis.docker.kubernetes.KubernetesPod
            - com.example.docker.DockerStandaloneHost
          label: Container Host
          description: >-
            Select an instance of Docker contaniner hosting provider to run the app
        - name: publish
          type: boolean
          label: Make application accessible from outside
          initial: true
          required: false
          description: >-
            Check if you intend to access application from the Internet

  - mongoConfig:
      fields:
        - name: mongoDB
          type: com.example.docker.DockerMongoDB
          label: MongoDB instance
          required: true
          description: >-
            Please select existing MongoDB instance or add a new one
