Namespaces:
  =: io.murano.apps.docker
  std: io.murano

Name: DockerPHPZendServer

Extends: DockerApplication

Properties:
  name:
    Contract: $.string().notNull()

  publish:
    Contract: $.bool().notNull()
    Default: true

  password:
    Contract: $.string().notNull()

  database:
    Contract: $.class(DockerMySQL).notNull()

  dbName:
    Contract: $.string().notNull()

  dbUser:
    Contract: $.string().notNull()

  dbPass:
    Contract: $.string().notNull()


Methods:
  initialize:
    Body:
      - $._environment: $.find(std:Environment).require()
      - $._scope: switch($.publish, $ => public, not $ => internal)


  getContainer:
    Body:
      - $.database.deploy()
      - $dbLink: $.getConnectionTo($.database, 3306)
      - Return:
          name: $.name
          image: 'php-zendserver'
          env:
            MYSQL_HOSTNAME: $dbLink.host
            MYSQL_PORT: $dbLink.port
            MYSQL_USERNAME: $.dbUser
            MYSQL_PASSWORD: $.dbPass
            MYSQL_DBNAME: $.dbName
            ZS_ADMIN_PASSWORD: $.password
          ports:
            - port: 80
              scope: $._scope
            - port: 10081
              scope: $._scope


  onInstallationStart:
    Body:
      - $._environment.reporter.report($this, 'Installing PHPZendServer')


  onInstallationFinish:
    Body:
      - If: $.publish
        Then:
          - $adminEndpoints: $.applicationEndpoints.where($.scope = $this._scope and $.containerPort = 10081).
              select(format('http://{0}:{1}', $.address, $.port))
          - $endpoints: $.applicationEndpoints.where($.scope = $this._scope and $.containerPort = 80).
              select(format('http://{0}:{1}', $.address, $.port))
          - $._environment.reporter.report($this, 'PHPZendServer {0} Admin UI is available at {1}'.format(
              $.name, join(', ', $adminEndpoints)))
          - $._environment.reporter.report($this, 'PHPZendServer {0} is available at {1}'.format(
              $.name, join(', ', $endpoints)))

        Else:
          - $._environment.reporter.report($this, 'PHPZendServer {0} has deployed but is not accessible from outside'.format($.name))
