#  Licensed under the Apache License, Version 2.0 (the "License"); you may
#  not use this file except in compliance with the License. You may obtain
#  a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.

Namespaces:
  =: io.murano.apps.docker
  std: io.murano

Name: DockerOrion

Extends: DockerApplication

Properties:
  name:
    Contract: $.string().notNull()

  publish:
    Contract: $.bool().notNull()
    Default: true

  mongodb:
    Contract: $.class(DockerMongoDB).notNull()

Methods:
  .init:
    Body:
      - $._environment: $.find(std:Environment).require()
      - $._scope: switch($.publish => public, true => internal)

  deploy:
    Body:
      - $.mongodb.deploy()
      - super($, $.deploy())

  getContainer:
    Body:
      - $mongoendopoint: $.getConnectionTo($.mongodb, 27017)
      - Return:
          name: $.name
          image: 'fiware/orion'
          env:
             MONGODB_HOST: $mongoendpoint.host
          ports:
            - port: 1026
              scope: $._scope
          commands: format('-dbhost {0}', $mongoendpoint.host)

  onInstallationStart:
    Body:
      - $._environment.reporter.report($this, 'Installing Orion')


  onInstallationFinish:
    Body:
      - If: $.publish
        Then:
          - $endpoints: $.applicationEndpoints.where($.scope = $this._scope).
              select(format('http://{0}:{1}', $.address, $.port))
          - $._environment.reporter.report($this, 'Orion {0} is available at {1}'.format($.name, $endpoints.join(', ')))
        Else:
          - $._environment.reporter.report($this, 'Orion {0} was deployed but is not accessible from outside'.format($.name))
