Version: 2
Templates:
  masterNode:
    ?:
      type: io.murano.apps.docker.kubernetes.KubernetesMasterNode
    instance:
      ?:
        type: io.murano.resources.LinuxMuranoInstance
      name: generateHostname($.appConfiguration.unitNamingPattern, 1)
      flavor: $.instanceConfiguration.flavor
      image: $.instanceConfiguration.osImage
      assignFloatingIp: $.appConfiguration.assignFloatingIP
      keyname: $.instanceConfiguration.keyPair
      availabilityZone: $.instanceConfiguration.availabilityZone

  minionNode:
    ?:
      type: io.murano.apps.docker.kubernetes.KubernetesMinionNode
    instance:
      ?:
        type: io.murano.resources.LinuxMuranoInstance
      name: generateHostname($.appConfiguration.unitNamingPattern, $index + 1)
      flavor: $.instanceConfiguration.flavor
      image: $.instanceConfiguration.osImage
      assignFloatingIp: $.appConfiguration.assignFloatingIP
      keyname: $.instanceConfiguration.keyPair
    enableMonitoring: $.appConfiguration.enableMonitoring


  gatewayNode:
    ?:
      type: io.murano.apps.docker.kubernetes.KubernetesGatewayNode
    instance:
      ?:
        type: io.murano.resources.LinuxMuranoInstance
      name: generateHostname($.appConfiguration.gatewayNamingPattern, $index)
      flavor: $.instanceConfiguration.flavor
      image: $.instanceConfiguration.osImage
      assignFloatingIp: $.appConfiguration.assignGatewayFloatingIP
      keyname: $.instanceConfiguration.keyPair

Application:
  ?:
    type: io.murano.apps.docker.kubernetes.KubernetesCluster
  name: $.appConfiguration.name
  masterNode: $masterNode
  minionNodes: repeat($minionNode, $.appConfiguration.maxMinionCount)
  nodeCount: $.appConfiguration.minionCount
  gatewayCount: $.appConfiguration.gatewayCount
  gatewayNodes: repeat($gatewayNode, $.appConfiguration.maxGatewayCount)


Forms:
  - appConfiguration:
      fields:
        - name: name
          type: string
          label: Application Name
          initial: Kubernetes Cluster
          description: >-
            Enter a desired name for the application. Just A-Z, a-z, 0-9, dash and
            underline are allowed
        - name: minionCount
          type: integer
          label: Initial/current number of minions
          initial: 3
          minValue: 1
          required: true
          description: >-
            Select number of minions
        - name: maxMinionCount
          type: integer
          label: Maximum number of minions
          initial: 3
          required: true
          minValue: 1
          description: >-
            Select maximum number of minions
        - name: assignFloatingIP
          type: boolean
          initial: true
          label: Assign floating IP for Kubernetes nodes
          description: >-
             Check to assign floating IP to Kubernetes nodes
          initial: false
          required: false
        - name: unitNamingPattern
          type: string
          initial: 'kube-#'
          required: false
          regexpValidator: '^(([a-zA-Z0-9#][a-zA-Z0-9-#]*[a-zA-Z0-9#])\.)*([A-Za-z0-9#]|[A-Za-z0-9#][A-Za-z0-9-#]*[A-Za-z0-9#])$'
          label: Kubernetes node hostname pattern
          widgetMedia:
            js: ['muranodashboard/js/support_placeholder.js']
            css: {all: ['muranodashboard/css/support_placeholder.css']}
        - name: enableMonitoring
          type: boolean
          initial: true
          required: false
          label: Enable cAdvisor monitoring
          description: >-
            Check to enable cAdvisor monitoring


        - name: gatewayCount
          type: integer
          label: Initial/current number of gateway nodes
          initial: 1
          minValue: 0
          required: true
          description: >-
            External traffic will be routed through gateway nodes
        - name: maxGatewayCount
          type: integer
          label: Maximum number of gateway nodes
          initial: 2
          required: true
          minValue: 0
          description: >-
            Maximum number of gateway nodes
        - name: assignGatewayFloatingIP
          type: boolean
          initial: true
          label: Assign floating IP for gateway nodes
          description: >-
             Check to assign floating IP to gateway nodes
          initial: false
          required: false
        - name: gatewayNamingPattern
          type: string
          initial: 'gateway-#'
          required: false
          regexpValidator: '^(([a-zA-Z0-9#][a-zA-Z0-9-#]*[a-zA-Z0-9#])\.)*([A-Za-z0-9#]|[A-Za-z0-9#][A-Za-z0-9-#]*[A-Za-z0-9#])$'
          label: Gateway hostname pattern
          widgetMedia:
            js: ['muranodashboard/js/support_placeholder.js']
            css: {all: ['muranodashboard/css/support_placeholder.css']}

  - instanceConfiguration:
      fields:
        - name: title
          type: string
          required: false
          hidden: true
          description: Specify some instance parameters on which application would be created
        - name: flavor
          type: flavor
          label: Instance flavor
          description: >-
            Select registered in Openstack flavor. Consider that application performance
            depends on this parameter.
          required: false
        - name: osImage
          type: image
          imageType: linux
          label: Instance image
          description: >-
            Select valid image for the application. Image should already be prepared and
            registered in glance.
        - name: keyPair
          type: keypair
          label: Key Pair
          description: >-
            Select the Key Pair to control access to instances. You can login to
            instances using this KeyPair after the deployment of application.
          required: false
        - name: availabilityZone
          type: azone
          label: Availability zone
          description: Select availability zone where the application would be installed.
          required: false
