Namespaces:
  =: io.murano.apps.docker
  std: io.murano

Name: DockerTomcat

Extends: DockerApplication

Properties:
  name:
    Contract: $.string().notNull()

  port:
    Contract: $.int().check($ > 0 and $ < 65536)

  publish:
    Contract: $.bool().notNull()
    Default: true

  password:
    Contract: $.string().notNull()


Methods:
  initialize:
    Body:
      - $._environment: $.find(std:Environment).require()
      - $._scope: switch($.publish, $ => public, not $ => internal)


  getContainer:
    Body:
      Return:
        name: $.name
        image: 'tutum/tomcat'
        env:
          TOMCAT_PASS: $.password
        ports:
          - port: $.port
            scope: $._scope


  onInstallationStart:
    Body:
      - $._environment.reporter.report($this, 'Installing Tomcat')


  onInstallationFinish:
    Body:
      - If: $.publish
        Then:
          - $endpoints: $.applicationEndpoints.where($.scope = $this._scope).
              select(format('http://{0}:{1}', $.address, $.port))
          - $._environment.reporter.report($this, 'Tomcat {0} is available at {1}'.format($.name, join(', ', $endpoints)))
        Else:
          - $._environment.reporter.report($this, 'Tomcat {0} has deployed but is not accessible from outside'.format($.name))
