#  Licensed under the Apache License, Version 2.0 (the "License"); you may
#  not use this file except in compliance with the License. You may obtain
#  a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.

Version: 2

Application:
  ?:
    type: io.murano.apps.docker.DockerJBoss
  name: $.appConfiguration.name
  host: $.appConfiguration.host
  publish: $.appConfiguration.publish
  password: $.appConfiguration.password


Forms:
  - appConfiguration:
      fields:
        - name: license
          type: string
          description: Apache License, Version 2.0
          hidden: true
          required: false
        - name: name
          type: string
          label: Application Name
          initial: 'DockerJBoss'
          description: >-
            Enter a desired name for the application. Just A-Z, a-z, 0-9, dash and
            underline are allowed
        - name: password
          type: password
          label: Admin Password
          description: Password for admin user in JBoss
        - name: host
          type:
            - io.murano.apps.docker.kubernetes.KubernetesPod
            - io.murano.apps.docker.DockerStandaloneHost
          label: Container Host
          description: >-
            Select an instance of Docker container hosting provider to run the app
        - name: publish
          type: boolean
          label: Make application accessible from outside
          initial: true
          required: false
          description: >-
            Check if you intend to access application from the Internet
