Format: 1.0
Type: Application
FullName: io.murano.apps.docker.kubernetes.KubernetesPod
Name: Kubernetes POD
Description: |
 Kubernes Pod - A collection of containers which will be scheduled onto the same node,
 which share and an IP and port space, and which can be created/destroyed together.
Author: 'Mirantis, Inc'
Tags: [docker, kubernetes, pod]
Classes:
 io.murano.apps.docker.kubernetes.KubernetesPod: KubernetesPod.yaml
