Version: 2

Application:
  ?:
    type: io.murano.apps.docker.DockerMongoDB
  name: $.appConfiguration.name
  host: $.appConfiguration.host
  port: 27017
  publish: $.appConfiguration.publish

Forms:
  - appConfiguration:
      fields:
        - name: name
          type: string
          label: Application Name
          initial: 'DockerMongoDB'
          description: >-
            Enter a desired name for the application. Just A-Z, a-z, 0-9, dash and
            underline are allowed
        - name: host
          type:
            - io.murano.apps.docker.kubernetes.KubernetesPod
            - io.murano.apps.docker.DockerStandaloneHost
          label: Container Host
          description: >-
            Select an instance of Docker contaniner hosting provider to run the app
        - name: publish
          type: boolean
          label: Make application accessible from outside
          initial: false
          required: true
          description: >-
            Check if you want to access application from internet
