Format: 1.0
Type: Application
FullName: io.murano.apps.docker.DockerNginxSite
Name: Docker Nginx Site
Description: |
 Deploys a site from a Git URL using Nginx as the web server.
Author: 'Mirantis, Inc'
Tags: [docker, application, Nginx]
Classes:
 io.murano.apps.docker.DockerNginxSite: DockerNginxSite.yaml
