#  Licensed under the Apache License, Version 2.0 (the "License"); you may
#  not use this file except in compliance with the License. You may obtain
#  a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.

Format: 1.0
Type: Application
FullName: com.example.docker.DockerPostgreSQL
Name: Docker Postgres
Description: |
 PostgreSQL, often simply “Postgres”, is an object-relational database management system (ORDBMS) with an emphasis on extensibility and standards-compliance. As a database server, its primary function is to store data, securely and supporting best practices, and retrieve it later, as requested by other software applications, be it those on the same computer or those running on another computer across a network (including the Internet).
Author: 'Mirantis, Inc'
Tags: [docker, application, Postgres]
Classes:
 com.example.docker.DockerPostgreSQL: DockerPostgreSQL.yaml
Require:
  com.example.docker.DockerStandaloneHost:
  com.mirantis.docker.kubernetes.KubernetesPod:
  com.mirantis.docker.Interfaces:
