#  Licensed under the Apache License, Version 2.0 (the "License"); you may
#  not use this file except in compliance with the License. You may obtain
#  a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.

Namespaces:
  =: com.example.docker
  std: io.murano
  interfaces: com.mirantis.docker

Name: DockerApp

Extends: interfaces:DockerApplication

Properties:
  name:
    Contract: $.string().notNull()

  publish:
    Contract: $.bool().notNull()
    Default: true

  env:
    Contract: $.string()

  image:
    Contract: $.string().notNull()

  ports:
    Contract: $.string().notNull()

Methods:
  .init:
    Body:
      - $._environment: $.find(std:Environment).require()
      - $._scope: switch($.publish => public, true => internal)
      - $._appPorts: $.ports.split(',').select(int($))


  getContainer:
    Body:
      Return:
        name: $.name
        image: $.image
        env: $._env2Map($.env)
        ports: $._appPorts.select(dict(port => $, scope => $this._scope))

  onInstallationStart:
    Body:
      - $._environment.reporter.report($this, 'Installing Application')


  onInstallationFinish:
    Body:
      - If: $.publish
        Then:
          - $endpoints: $.applicationEndpoints.
              where($.scope = $this._scope).
              select(format('{0}:{1}', $.address, $.port))

          - $._environment.reporter.report($this, 'Application {0} is available at {1}'.format(
              $.name, $endpoints.join(', ')))
        Else:
          - $._environment.reporter.report($this, 'Application {0} has deployed but is not accessible from outside'.format($.name))

  _env2Map:
    Arguments:
      envString:
        Contract: $.string().notNull()
    Body:
      - $result: {}
      - For: t
        In: $envString.split(',')
        Do:
          - $pair: $t.split('=')
          - If: len($pair) < 2
            Then:
              Continue:
          - $key: $pair[0].trim()
          - $result[$key]: $pair[1].trim()
      - Return: $result