#  Licensed under the Apache License, Version 2.0 (the "License"); you may
#  not use this file except in compliance with the License. You may obtain
#  a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.

Version: 2

Application:
  ?:
    type: com.example.docker.DockerStandaloneHost
  name: $.appConfiguration.name
  dockerRegistry: $.appConfiguration.dockerRegistry
  dockerMirror: $.appConfiguration.dockerMirror
  gcloudKey: $.appConfiguration.gcloudKey
  instance:
    ?:
      type: io.murano.resources.LinuxMuranoInstance
    name: generateHostname($.instanceConfiguration.unitNamingPattern, 1)
    flavor: $.instanceConfiguration.flavor
    image: 'ubuntu14.04-x64-docker'
    keyname: $.instanceConfiguration.keyPair
    assignFloatingIp: $.appConfiguration.assignFloatingIP
    availabilityZone: $.instanceConfiguration.availabilityZone

Forms:
  - appConfiguration:
      fields:
        - name: license
          type: string
          description: Apache License, Version 2.0
          hidden: true
          required: false
        - name: name
          type: string
          label: Application Name
          initial: Docker Standalone Host
          description: >-
            Enter a desired name for the application. Just A-Z, a-z, 0-9, dash and
            underline are allowed
        - name: assignFloatingIP
          type: boolean
          label: Assign Floating IP
          description: >-
             Select to true to assign floating IP automatically
          initial: true
          required: false
        - name: dockerRegistry
          type: string
          label: Custom Docker registry URL
          description: >-
            Host IP or domain name of custom Docker registry to use. Leave empty for Docker default
          required: false
        - name: dockerMirror
          type: string
          label: Docker registry mirror URL
          description: >-
            URL of Docker registry mirror to use. Leave empty to not use one
          required: false
        - name: gcloudKey
          type: string
          label: Google registry key
          regexpValidator: '^{(\s*"(\\(["\\\/bfnrt]|u[a-fA-F0-9]{4})|[^"\\\0-\x1F\x7F]+)*"\s*:\s*"(\\(["\\\/bfnrt]|u[a-fA-F0-9]{4})|[^"\\\0-\x1F\x7F]+)*"\s*(,|\s*}$))*$'
          errorMessages:
            invalid: Text should be a valid JSON.
          description: >-
            Contents of JSON key file. Used to authenticate to the Google Container Registry
          required: false

  - instanceConfiguration:
      fields:
        - name: title
          type: string
          required: false
          hidden: true
          description: Specify some instance parameters on which the application would be created
        - name: flavor
          type: flavor
          label: Instance flavor
          description: >-
            Select registered in Openstack flavor. Consider that application performance
            depends on this parameter.
          required: false
          requirements:
            min_disk: 10
            min_memory_mb: 1024
            min_vcpus: 1
        - name: keyPair
          type: keypair
          label: Key Pair
          description: >-
            Select a Key Pair to control access to instances. You can login to
            instances using this KeyPair after the deployment of application.
          required: false
        - name: availabilityZone
          type: azone
          label: Availability zone
          description: Select availability zone where the application would be installed.
          required: false
        - name: unitNamingPattern
          label: Hostname
          type: string
          required: false
