Namespaces:
  =: io.murano.apps.docker
  std: io.murano

Name: DockerGuestBook

Extends: DockerApplication

Properties:
  name:
    Contract: $.string().notNull()

  port:
    Contract: $.int().check($ > 0 and $ < 65536)
    Default: 80

  publish:
    Contract: $.bool().notNull()
    Default: true

  redisMaster:
    Contract: $.class(DockerRedis).notNull()

  redisSlave:
    Contract: $.class(DockerRedisSlave).notNull()


Methods:
  initialize:
    Body:
      - $._environment: $.find(std:Environment).require()
      - $._scope: switch($.publish, $ => public, not $ => internal)


  getContainer:
    Body:
      - $.redisMaster.deploy()
      - $.redisSlave.deploy()
      - $redisMasterLink: $.getConnectionTo($.redisMaster, $.redisMaster.port)
      - $redisSlaveLink: $.getConnectionTo($.redisSlave, $.redisSlave.port)
      - Return:
          name: $.name
          image: 'brendanburns/php-redis'
          env:
            REDIS_MASTER_SERVICE_HOST: $.redisMaster.host
            REDIS_MASTER_SERVICE_PORT: $.redisMaster.port
            REDISSLAVE_SERVICE_HOST: $.redisSlave.host
            REDISSLAVE_SERVICE_PORT: $.redisSlave.port
          ports:
            - port: $.port
              scope: $._scope


  onInstallationStart:
    Body:
      - $._environment.reporter.report($this, 'Installing Redis Slave')


  onInstallationFinish:
    Body:
      - If: $.publish
        Then:
          - $endpoints: $.applicationEndpoints.where($.scope = $this._scope).
              select(format('{0}:{1}', $.address, $.port))
          - $._environment.reporter.report($this, 'GuestBook {0} is available at {1}'.format($.name, join(', ', $endpoints)))
        Else:
          - $._environment.reporter.report($this, 'GuestBook {0} has deployed but is not accessible from outside'.format($.name))
