Namespaces:
  =: io.murano.apps.docker
  std: io.murano

Name: DockerRedisSlave

Extends: DockerApplication

Properties:
  name:
    Contract: $.string().notNull()

  port:
    Contract: $.int().check($ > 0 and $ < 65536)
    Default: 6379

  publish:
    Contract: $.bool().notNull()
    Default: true

  redisMaster:
    Contract: $.class(DockerRedis).notNull()


Methods:
  initialize:
    Body:
      - $._environment: $.find(std:Environment).require()
      - $._scope: switch($.publish, $ => public, not $ => internal)


  getContainer:
    Body:
      - $redisMasterLink: $.getConnectionTo($.redisMaster, $.redisMaster.port)
      - Return:
          name: $.name
          image: 'brendanburns/redis-slave'
          env:
            REDIS_MASTER_SERVICE_HOST: $redisMaster.host
            REDIS_MASTER_SERVICE_PORT: $redisMaster.port
          ports:
            - port: $.port
              scope: $._scope


  onInstallationStart:
    Body:
      - $._environment.reporter.report($this, 'Installing RedisSlave')


  onInstallationFinish:
    Body:
      - If: $.publish
        Then:
          - $endpoints: $.applicationEndpoints.where($.scope = $this._scope).
              select(format('{0}:{1}', $.address, $.port))
          - $._environment.reporter.report($this, 'Redis Slave {0} is available at {1}'.format($.name, join(', ', $endpoints)))
        Else:
          - $._environment.reporter.report($this, 'Redis Slave {0} has deployed but is not accessible from outside'.format($.name))
