Namespaces:
  =: io.murano.apps.docker
  std: io.murano

Name: DockerMongoDB

Extends: std:Application

Properties:
  name:
    Contract: $.string().notNull()
  host:
    Contract: $.class(DockerContainerHost).notNull()
  port:
    Contract: $.int().check($ > 0 and $ < 65536)


Methods:
  initialize:
    Body:
      - $._environment: $.find(std:Environment).require()

  deploy:
    Body:
      - If: not $.getAttr(deployed, false)
        Then:
          - $._environment.reporter.report($this, 'Installing Application')
          - $.host.hostContainer(
                name => $.name,
                image => mongo,
                commands => list(),
                env => dict(),
                ports => list($.port),
                volumes => dict()
              )
          - $.host.deploy()
          
          - $._environment.reporter.report($this, 'Application MongoDB available at {0}:{1}'.format($.host.getIp(), $.port))
          - $.setAttr(deployed, true)

