Version: 2

Application:
  ?:
    type: io.murano.apps.docker.DockerHTTPd
  name: $.appConfiguration.name
  host: $.appConfiguration.host 
  port: $.appConfiguration.port


Forms:
  - appConfiguration:
      fields:
        - name: name
          type: string
          label: Application Name
          initial: 'DockerHTTPd'
          description: >-
            Enter a desired name for the application. Just A-Z, a-z, 0-9, dash and
            underline are allowed
        - name: host
          type: io.murano.apps.docker.kubernetes.KubernetesPod
          label: Container Host
          description: >-
            Select an instance of Docker contaniner to run the app
        - name: port
          type: integer
          label: Port
          description: >-
            Select a port to run the app

