Format: 1.0
Type: Application
FullName: io.murano.apps.docker.DockerCrate
Name: Docker Crate
Description: |
 Crate is an Elastic SQL Data Store. Distributed by design, Crate makes centralized database servers obsolete. Realtime non-blocking SQL engine with full blown search. Highly available, massively scalable yet simple to use.
Author: 'Mirantis, Inc'
Tags: [docker, application, crate]
Classes:
 io.murano.apps.docker.DockerCrate: DockerCrate.yaml
